### ISSUE TITLE
Potential Query Error

### ISSUE THREAD

**Issue by WaterKH** [WaterKH/WayfinderProjectAPI#53]
```[wayfinderprojectapi] [2022-11-27 00:19:56] fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
[wayfinderprojectapi] [2022-11-27 00:19:56]       Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
[wayfinderprojectapi] [2022-11-27 00:19:56]       SELECT `m`.`Id`, `g`.`Id`, `g`.`Name`, `m`.`Name`, `m`.`Link`, `t`.`Id`, `t`.`Name`, `t`.`ScenesId`, `t`.`WorldsId`, `t0`.`Id`, `t0`.`Name`, `t0`.`CharactersId`, `t0`.`ScenesId`, `t1`.`Id`, `t1`.`Name`, `t1`.`AreasId`, `t1`.`ScenesId`, `t2`.`Id`, `t2`.`Name`, `t2`.`Link`, `t2`.`MusicId`, `t2`.`ScenesId`, `m`.`Notes`
[wayfinderprojectapi] [2022-11-27 00:19:56]       FROM `MA_Scene` AS `m`
[wayfinderprojectapi] [2022-11-27 00:19:56]       INNER JOIN `Games` AS `g` ON `m`.`GameId` = `g`.`Id`
[wayfinderprojectapi] [2022-11-27 00:19:56]       LEFT JOIN (
[wayfinderprojectapi] [2022-11-27 00:19:56]           SELECT `w`.`Id`, `w`.`Name`, `s`.`ScenesId`, `s`.`WorldsId`
[wayfinderprojectapi] [2022-11-27 00:19:56]           FROM `SceneWorld` AS `s`
[wayfinderprojectapi] [2022-11-27 00:19:56]           INNER JOIN `Worlds` AS `w` ON `s`.`WorldsId` = `w`.`Id`
[wayfinderprojectapi] [2022-11-27 00:19:56]       ) AS `t` ON `m`.`Id` = `t`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]       LEFT JOIN (
[wayfinderprojectapi] [2022-11-27 00:19:56]           SELECT `c0`.`Id`, `c0`.`Name`, `c`.`CharactersId`, `c`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]           FROM `CharacterScene` AS `c`
[wayfinderprojectapi] [2022-11-27 00:19:56]           INNER JOIN `Characters` AS `c0` ON `c`.`CharactersId` = `c0`.`Id`
[wayfinderprojectapi] [2022-11-27 00:19:56]       ) AS `t0` ON `m`.`Id` = `t0`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]       LEFT JOIN (
[wayfinderprojectapi] [2022-11-27 00:19:56]           SELECT `a0`.`Id`, `a0`.`Name`, `a`.`AreasId`, `a`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]           FROM `AreaScene` AS `a`
[wayfinderprojectapi] [2022-11-27 00:19:56]           INNER JOIN `Areas` AS `a0` ON `a`.`AreasId` = `a0`.`Id`
[wayfinderprojectapi] [2022-11-27 00:19:56]       ) AS `t1` ON `m`.`Id` = `t1`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]       LEFT JOIN (
[wayfinderprojectapi] [2022-11-27 00:19:56]           SELECT `m1`.`Id`, `m1`.`Name`, `m1`.`Link`, `m0`.`MusicId`, `m0`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]           FROM `MusicScene` AS `m0`
[wayfinderprojectapi] [2022-11-27 00:19:56]           INNER JOIN `Music` AS `m1` ON `m0`.`MusicId` = `m1`.`Id`
[wayfinderprojectapi] [2022-11-27 00:19:56]       ) AS `t2` ON `m`.`Id` = `t2`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56]       WHERE FALSE
[wayfinderprojectapi] [2022-11-27 00:19:56]       ORDER BY `m`.`Id`, `g`.`Id`, `t`.`ScenesId`, `t`.`WorldsId`, `t`.`Id`, `t0`.`CharactersId`, `t0`.`ScenesId`, `t0`.`Id`, `t1`.`AreasId`, `t1`.`ScenesId`, `t1`.`Id`, `t2`.`MusicId`, `t2`.`ScenesId`
[wayfinderprojectapi] [2022-11-27 00:19:56] fail: Microsoft.EntityFrameworkCore.Query[10100]
[wayfinderprojectapi] [2022-11-27 00:19:56]       An exception occurred while iterating over the results of a query for context type 'WayfinderProjectAPI.Data.WayfinderContext'.
[wayfinderprojectapi] [2022-11-27 00:19:56]       System.NullReferenceException: Object reference not set to an instance of an object.
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 493
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 77
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 345
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 337
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[wayfinderprojectapi] [2022-11-27 00:19:56]       System.NullReferenceException: Object reference not set to an instance of an object.
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 493
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 77
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 345
[wayfinderprojectapi] [2022-11-27 00:19:56]          at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 337
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
[wayfinderprojectapi] [2022-11-27 00:19:56]          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

I believe all that need to be done here is just check for NULL value from search, but the way we search things, this should never happen.

**Comment by WaterKH** [comment]
There's a WHERE FALSE at the end, not sure where this is being called though.

**Comment by WaterKH** [comment]
I believe this was an error being thrown by #54 - If not, I can re-open and continue investigation.
